### ISSUE TITLE
docs

### ISSUE THREAD

**Issue by joaoalves** [dendrograms/astrodendro#118]
Dear friends,

I'm trying to download the docs (summer reading) but something is not working. The PDF version is a Figure and the ePub does not open in iBooks, giving the following error:

“This page contains the following errors:

error on line 60 at column 10: Opening and ending tag mismatch: link line 0 and head
”

Excerpt From: unknown. “astrodendro 0.0.0 documentation.” iBooks. https://itunes.apple.com/WebObjects/MZStore.woa/wa/viewBook?id=05EB9ACAF8383DB2CD2DF716EC6A9A24

Thanks for your efforts in building great and useful software!
Joao

**Comment by astrofrog** [comment]
This should now be fixed
