### ISSUE TITLE
Fluxes in PPVstatistic

### ISSUE THREAD

**Issue by low-sky** [dendrograms/astrodendro#150]
Remy I. pointed out that PPVstatistic returns the sum of pixel values (i.e., the flux density) as the flux and it isn't multiplied by a frequency equivalent to turn it into a proper flux (in Jy Hz or equivalent).  It's probably also work checking what happens for surface brightness units and changing to integrated intensities.

**Comment by keflavich** [comment]
I handle all these things manually, but better support inside astrodendro would be good. :+1:

**Comment by tomr-stargazer** [comment]
See issue #107 for our 2 year old discussion on this topic (:

**Comment by low-sky** [comment]
@tomr-stargazer -- Good point.  I'll close and just keep it on that.  Clearly well forgotten by my feeble brain.
