### ISSUE TITLE
same indices, different data?

### ISSUE THREAD

**Issue by indebetouw** [dendrograms/astrodendro#154]
I am interested in computing a dendrogram using one cube, and then calculating a PPVCatalog using the same assignment indices, but a different data cube.  I've tried setting the .data, ._data, and some other things, but is there a way to re-index, or re-fill all of the individual structures' values, without recomputing?   Yes, I know the heirarchical nature of the dendrogram is no longer necessarily self-consistent if I apply it to a new data cube, but I want to compare different emission lines over exactly the same regions.   Thanks.

**Comment by keflavich** [comment]
@indebetouw if your cubes have the same shape, you can access the mask for an individual structure with the `.get_mask` attribute, e.g.:

**Comment by keflavich** [comment]
@indebetouw if your cubes have the same shape, you can access the mask for an individual structure with the `.get_mask` attribute, e.g.:
https://github.com/keflavich/APEX_CMZ_H2CO/blob/master/analysis/dendro_temperature.py#L150

From that mask, you can then compute various attributes (e.g., sum, mean, etc.) of the other molecules and add them to your catalog as in the example script linked.

**Comment by indebetouw** [comment]
Thanks Adam!  Is the view and submask in that script just for speed, or am I missing something critical about doing that way?  I liked the Formaldehyde paper too BTW.

**Comment by keflavich** [comment]
Yes, the submask is just for speed.  Thanks!
