### ISSUE TITLE
Importing "Iterable" needs updating for Python > 3.9

### ISSUE THREAD

**Issue by nbrunett** [dendrograms/astrodendro#183]
I was trying to run [`pycprops`](https://github.com/PhangsTeam/pycprops) in Python 3.10.2 (which uses `astrodendro`) and encountered the following import error (partial traceback to exclude my scripts and directory names):

```
File ".../astrodendro/__init__.py", line 3
    from .dendrogram import Dendrogram, periodic_neighbours
File ".../astrodendro/dendrogram.py", line 8
    from collections import Iterable
ImportError: cannot import name 'Iterable' from 'collections'
```

It looks like importing `Iterable` from `collections` has changed after Python 3.9 (see text below the first table at the top of the page [here](https://docs.python.org/3.9/library/collections.html)).

Changing line 8  in `dendrogram.py` from

```python
from collections import Iterable
```

to

```python
try:
    # Python <= 3.9
    from collections import Iterable
except ImportError:
    # Python > 3.9
    from collections.abc import Iterable
```

eliminated the problem for me (inspired by suggestion in the comment [here](https://github.com/Azure/azure-cli/issues/20444#issuecomment-1009648464)).

Let me know if you need any more information.

**Comment by keflavich** [comment]
could you please submit this as a pull request?
