### ISSUE TITLE
Release 0.2 package

### ISSUE THREAD

**Issue by astrofrog** [dendrograms/astrodendro#55]
GitHub will close the milestone if all issues are completed, so this ensures that the milestone stays open until the package is actually released. Leave any reminders here about anything release-related.

**Comment by keflavich** [comment]
@astrofrog - there have been some changes since July 2013.  Can we go ahead with a new release with what currently exists?  cc @e-koch

**Comment by astrofrog** [comment]
Yes, I can do this later today.

**Comment by astrofrog** [comment]
This is now done! Sorry for the delay!
